### ISSUE TITLE
Support more TxStopPoint and TxStartPoint s.

### ISSUE THREAD

**Issue by maaikez** [EVerest/libocpp#321]
Currently we only support TxStopPoint EvConnected,Authorized and TxStartPoint PowerPathClosed. We would like to support more / all TxStopPoint and TxStartPoint s.

**Comment by thanaParis** [comment]
Has there been any progress on this? Looking to test a use case with EVerest that requires TxStartPoint EvConnected.

**Comment by Pietfried** [comment]
Hi @thanaParis , `TxStartPoint` and `TxStopPoint` are configurable in EVerest since https://github.com/EVerest/everest-core/pull/611 , we missed to close this issue.

The main part of the business logic for this is implemented in everest-core, which is responsible for triggering the TransactionEvent(Started) / TransactionEvent(Ended).

You can configure `TxStartPoint` and `TxStopPoint` here: https://github.com/EVerest/libocpp/blob/main/config/v201/config.json#L463
