### ISSUE TITLE
Build for libocpp failed.

### ISSUE THREAD

**Issue by RichardWQJ** [EVerest/libocpp#433]
Hi professors,
    I build for libocpp failed recently, due to error parameter of  "on_session_started" in "src/charge_point.cpp" at line 280.
    The parameter 2 should be a enum: ocpp::SessionStartedReason::EVConnected, not a string variable "EVConnected".

**Comment by Pietfried** [comment]
Hi, thanks for pointing this out. The build examples are not yet included in the CI, so that slipped through. There might be some more issues with the build examples, because they haven't really been maintained in the past. Ill put the question about maintaining (or removing) on the agenda for the next working group meeting.
