### ISSUE TITLE
Unable to successfully run `generate_component_schemas.py`

### ISSUE THREAD

**Issue by couryrr-afs** [EVerest/libocpp#752]
# Description

While attempting to address this PR comment https://github.com/EVerest/libocpp/pull/746/files#r1719052885 we were trying to run the `generate_component_schemas.py`. Based on the README.md a modified version of the `dm_component_vars.csv` is used. The version of the modified CSV is not checked into source control therefore trying to run the generator does not succeed.

Likewise, there are dependencies that are required to run the `generate_component_schemas.py` that are not called out in the README.md or captured in a requirements.txt.

# Request

Check in the modified version of `dm_component_vars.csv`
Add a comment or requirements.txt for the needed dependencies.

**Comment by Pietfried** [comment]
> # Description
> While attempting to address this PR comment https://github.com/EVerest/libocpp/pull/746/files#r1719052885 we were trying to run the `generate_component_schemas.py`. Based on the README.md a modified version of the `dm_component_vars.csv` is used. The version of the modified CSV is not checked into source control therefore trying to run the generator does not succeed.
> 
> Likewise, there are dependencies that are required to run the `generate_component_schemas.py` that are not called out in the README.md or captured in a requirements.txt.
> 
> # Request
> Check in the modified version of `dm_component_vars.csv` Add a comment or requirements.txt for the needed dependencies.

Hi @couryrr-afs,

We started with an unmodified version of the `dm_component_vars.csv` and then changed it because we were missing some properties in there. We can't push it because the license doesn't allow modifications. We used it mainly for the initial generation of the schemas and `ctrlr_component_variables` and the `config.json` files but decided to modfiy those manually in the future. We will therefore drop the generation scripts for v201 soon.
